### ISSUE TITLE
'weak' is no optional dependency

### ISSUE THREAD

**Issue by dodekeract** [substack/dnode#157]
```` npm install --no-optional dnode ````

````
module.js:333
    throw err;
          ^
Error: Cannot find module 'weak'
    at Function.Module._resolveFilename (module.js:331:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at new D (dnode\index.js:28:20)
    at module.exports (dnode\index.js:8:12)
    at Object.<anonymous> (app.js:2:14)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
````

I'm not installing 'weak', because it apparently fails building with node-gyp for me.
(OS: Windows 7 Ultimate x64)

**Comment by Chrisbon** [comment]
Me too - anyone know if this is going to be fixed?

C:\Users\W7\My Source\nodejs\nodebot\workshop>npm install dnode
|
> weak@0.3.4 install C:\Users\W7\My Source\nodejs\nodebot\workshop\node_modules\
dnode\node_modules\weak
> node-gyp rebuild
 
 
C:\Users\W7\My Source\nodejs\nodebot\workshop\node_modules\dnode\node_modules\we
ak>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
odules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'weakref.vcxproj' is in
valid. Platform='x64'. You may be seeing this message because you are trying t
o build a project without a solution file, and have specified a non-default Pla
tform that doesn't exist for this project. [C:\Users\W7\My Source\nodejs\nodebo
t\workshop\node_modules\dnode\node_modules\weak\build\weakref.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack at ChildProcess.emit (events.js:110:17)
gyp ERR! stack at Process.ChildProcess._handle.onexit (child_process.js:1067
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\W7\My Source\nodejs\nodebot\workshop\node_modules\dnode\no
de_modules\weak
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing weak@0.3.4
dnode@1.2.0 node_modules\dnode
├── jsonify@0.0.0
└── dnode-protocol@0.2.2 (traverse@0.6.6)

**Comment by dodekeract** [comment]
@Chrisbon I don't know if you actually need weak. But you should probably try ````npm install --no-optional dnode````. The issue that weak isn't optional seems to be fixed by https://github.com/substack/dnode/commit/34d1c9aa9696f13bdf8fb99d9d039367ad873f90. In the changes of that patch you can see that there now is an option to disable weak usage by setting ````weak: false````.
